name: Update Trading Data
on:
  schedule:
    - cron: '*/45 * * * *'  # Every 45 minutes
  workflow_dispatch:        # Manual trigger
  push:                     # Run on code changes
    branches: [ main ]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Fetch Live Trading Data
        run: node fetch-data.js
        
      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add data/ || echo "No data directory yet"
          git commit -m "🚀 Update live trading data - $(date)" || echo "No changes to commit"
          git push || echo "Nothing to push"
